extends:
  - '@form8ion'
  - '@form8ion/mocha'
  - '@form8ion/cucumber'

rules:
  import/extensions:
    - error
    - ignorePackages

overrides:
  - files: example.js
    rules:
      import/no-extraneous-dependencies: 'off'
