name: Release
'on':
  push:
    branches:
      - alpha
  workflow_dispatch: {}
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Setup node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - name: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
